version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: ai-medical-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads
      - ./gradcam_results:/app/gradcam_results
      - ./reports:/app/reports

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: ai-medical-frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend