# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install Linux dependencies required by OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Create folders
RUN mkdir -p uploads gradcam_results reports

# Expose Flask port
EXPOSE 5000

# Run Flask
CMD ["python", "app.py"]